#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx      
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null   
echo "server {
        listen 80 default_server;  
        root /var/www/html;        
        index index.html;
        location / {
		add_header X-Served-By $hostname;
                try_files $uri $uri/ =404;
        }
}"| sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx start
