#!/usr/bin/env bash
# This script configures a new Ubuntu machine with Nginx to include a custom HTTP response header.

# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

set -e

# echo "Updating package list..."
sudo apt-get -y update

# echo "Installing Nginx..."
sudo apt-get -y install nginx

# echo "Creating backup of the default Nginx config..."
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

# echo "Creating custom HTML file..."
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# echo "Creating new Nginx config..."
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}
EOF'

sudo service nginx restart
