#!/usr/bin/env bash

# Ensure script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root" >&2
    exit 1
fi

# Update package repositories
apt-get update

# Install HAProxy
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

# Enable HAProxy service
sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Configure HAProxy
cat <<EOF >> /etc/haproxy/haproxy.cfg
listen balancer
    bind :80
    balance roundrobin
    server 5145-web-01 54.146.57.1:80 check
    server 5145-web-02 54.157.177.67:80 check
EOF

# Restart HAProxy service
service haproxy restart
