#!/usr/bin/env bash
#Bash script that creates a subprocess
#. /lib/lsb/init-functions

INIT_FUNCTIONS="/lib/lsb/init-functions"

#check if the file exoists
if [ ! -e "$INIT_FUNCTIONS" ]; then
	echo "Error: $INIT_FUNCTIONS not found." >$2
	exit 1
fi

#Source the init-functions file
. "$INIT_FUNCTIONS"

PIDFILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$PIDFILE"
}

stop() {
    sudo kill -15 "$(cat "$PIDFILE")" && rm -f "$PIDFILE"
}

case "$1" in 
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
