#!/usr/bin/env bash
# Display badluck for 4th loop
# Display goodluck for 8th loop
# Display Best school for other

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
