#!/usr/bin/env bash
#check if the script is run with sudo/root privileges
if [[  $EUID -ne 0 ]]; then
  echo "Please run this script with sudo or as root."
  exit 1
fi

#Backup the current hosts file
cp /etc/hosts /etc/hosts.bak

#Add entries to the hosts file
echo "127.0.0.2	localhost" >> /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
